name: ci

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/python-app:${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: arc-runner-set
    steps:
      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -k -sSL -o argocd-linux-amd64 https://argcd-argocd-server.argocd/donwloads/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          mv ./argocd-linux-amd64 /usr/local/bin/argocd
      - name: ArgoCD Login
        shell: bash
        run: |
          argocd login argcd-argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username ${{ vars.ARGOCD_USER }} \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

